#!/usr/bin/env python
# coding: utf-8

# In[1]:


name="Sami"


# In[2]:


last_letter=name[1:]


# In[3]:


last_letter


# In[1]:


7/4


# In[2]:


(8-2)%(4-2)


# In[1]:


a = 5


# In[2]:


a


# In[3]:


a = 10


# In[4]:


a + a


# In[5]:


my_income = 100

tax_rate = 0.1

my_tax = my_income * tax_rate


# In[6]:


my_tax


# In[7]:


print("hello my name is Sami")


# In[9]:


print("hello my name is Sami")


# In[13]:


print("hellp my name is \tSami")


# In[14]:


mystring = "Hello World"


# In[15]:


mystring


# In[16]:


mystring[0]


# In[17]:


mystring[8]


# In[18]:


mystring[9]


# In[19]:


mystring[-2]


# In[20]:


mystring[-4]


# In[21]:


mystring= "abcdefghijk"


# In[22]:


mystring


# In[23]:


mystring[3:]


# In[25]:


mystring[3:6]

mystring
# In[1]:


mystring = "abcdefghijkl"


# In[2]:


mystring


# In[4]:


mystring[1:3]


# In[5]:


mystring[6:9]


# In[6]:


mystring[-6:-3]


# In[7]:


mystring[::]


# In[11]:


mystring[::-1]


# In[12]:


name = "Sami"


# In[13]:


name


# In[15]:


last_letters=name[1:]


# In[16]:


last_letters


# In[17]:


'P' + last_letters


# In[18]:


x = 'Hello World'


# In[20]:


x= x + ", my name is Sami"


# In[21]:


x


# In[22]:


x = 'Hello World'


# In[23]:


x


# In[24]:


x.upper()


# In[25]:


x.split()


# In[27]:


print('This is a string {}'.format('INSERTED'))


# In[30]:


print ('The {2} {1} {0}'.format('fox', 'brown', 'quick'))

result = 100/777
# In[31]:


result


# In[32]:


result = 100/777


# In[33]:


result


# In[44]:


print("The final result is {r:1.3f}".format(r=result))


# In[45]:


mylist= ['One', 'Two', 'Three']


# In[46]:


new_list= ['Four', 'Five']


# In[48]:


mynew_list= mylist+new_list


# In[49]:


mynew_list


# In[50]:


mynew_list[0] = "ALL CAPS"


# In[51]:


mynew_list


# In[52]:


mynew_list.append('six')


# In[53]:


mynew_list


# In[54]:


mynew_list.append("Seven")


# In[55]:


mynew_list


# In[56]:


mynew_list.pop()


# In[57]:


mynew_list


# In[58]:


popped_item= mynew_list.pop()


# In[60]:


popped_item


# In[61]:


mynew_list


# In[62]:


new_list= ['a','e', 'x', 'b', 'c']
num_list= [4,1,8,3]


# In[65]:


new_list.sort()
sorted_list= new_list


# In[64]:


new_list


# In[66]:


sorted_list


# In[67]:


num_list


# In[70]:


num_list.sort()
newnum_list= num_list


# In[69]:


num_list


# In[71]:


newnum_list


# In[72]:


mynew_list.reverse()


# In[73]:


mynew_list


# In[74]:


newnum_list.reverse()


# In[75]:


newnum_list


# In[77]:


my_dict = {'key1' : 'value1', 'key2' : 'value2'}


# In[78]:


my_dict


# In[79]:


my_dict['key1']


# In[82]:


my_dict['key2']


# In[83]:


prices_lookup= {'apples':2.99, 'orange':1.99, 'milk':5.80 }


# In[85]:


prices_lookup['apples']


# In[86]:


prices_lookup['milk']


# In[88]:


d = {'k1':123, 'k2': [0,1,2], 'k3':100}


# In[89]:


d['k2']


# In[90]:


d['k3']


# In[92]:


d['k2'][2]


# In[93]:


d= {'key1':['a','b','c']}


# In[94]:


d


# In[95]:


mylist= d['key1']


# In[96]:


mylist


# In[97]:


letter = mylist[2]


# In[98]:


letter


# In[99]:


letter.upper()


# In[100]:


d


# In[102]:


d['key1'][2].upper()


# In[103]:


d= {'k1':100, 'k2': 200}


# In[104]:


d


# In[105]:


d['k3']= 300


# In[106]:


d


# In[108]:


d['k1']= 'New Value'


# In[109]:


d


# In[110]:


d= {'k1': 100, 'k2': 200, 'k3': 300}


# In[111]:


d


# In[113]:


d.values()


# In[115]:


d.items()


# In[ ]:




